# Generated by Django 5.1.4 on 2026-04-06 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('pr_review', '0001_initial'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1024)),
                ('rule_name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_violations', to='ingestion.commit')),
                ('pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_violations', to='pr_review.pullrequest')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_violations', to='repositories.repository')),
            ],
            options={
                'indexes': [models.Index(fields=['repo', 'severity', '-created_at'], name='rules_rulev_repo_id_136315_idx'), models.Index(fields=['repo', 'rule_name'], name='rules_rulev_repo_id_75f4b5_idx'), models.Index(fields=['repo', 'language'], name='rules_rulev_repo_id_f5b685_idx')],
            },
        ),
    ]
