# Generated by Django 5.1.4 on 2026-04-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_setup_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrepository',
            options={'verbose_name': 'User Repository', 'verbose_name_plural': 'User Repositories'},
        ),
    ]
