# Generated by Django 5.1.4 on 2026-04-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_alter_userrepository_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='pr_review_enabled',
            field=models.BooleanField(default=True, help_text='When False, Stratum will not comment on new PRs for this repository.'),
        ),
    ]
