# Generated by Django 5.1.4 on 2026-04-07 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_id', models.UUIDField(db_index=True)),
                ('task_name', models.CharField(max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repo_id'], name='dashboard_f_repo_id_847203_idx')],
            },
        ),
        migrations.CreateModel(
            name='PipelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_id', models.UUIDField(db_index=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('items_processed', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repo_id', 'stage'], name='dashboard_p_repo_id_332e2b_idx'), models.Index(fields=['repo_id', 'created_at'], name='dashboard_p_repo_id_6a34f9_idx')],
            },
        ),
    ]
