# Generated by Django 5.1.4 on 2026-04-06 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlameMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debt_introduced_score', models.FloatField(default=0.0)),
                ('patterns_originated', models.IntegerField(default=0)),
                ('files_eventually_affected', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blame_map', to='ingestion.commit')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blame_maps', to='repositories.repository')),
            ],
            options={
                'indexes': [models.Index(fields=['repo', '-debt_introduced_score'], name='blame_blame_repo_id_8095d4_idx')],
            },
        ),
    ]
