# Generated by Django 5.1.4 on 2026-04-06 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('parsing', '0001_initial'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('centroid_hash', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('first_seen_at', models.DateTimeField()),
                ('file_count', models.IntegerField(default=0)),
                ('chunk_count', models.IntegerField(default=0)),
                ('growth_rate', models.FloatField(default=0.0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('origin_commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_clusters', to='ingestion.commit')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='repositories.repository')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='parsing.codechunk')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clustering.semanticcluster')),
            ],
        ),
        migrations.AddIndex(
            model_name='semanticcluster',
            index=models.Index(fields=['repo', 'language'], name='clustering__repo_id_2f5a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticcluster',
            index=models.Index(fields=['repo', 'is_flagged'], name='clustering__repo_id_e9526b_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticcluster',
            index=models.Index(fields=['repo', '-growth_rate'], name='clustering__repo_id_b4fa9d_idx'),
        ),
        migrations.AddIndex(
            model_name='clustermembership',
            index=models.Index(fields=['cluster', '-similarity_score'], name='clustering__cluster_468b1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clustermembership',
            unique_together={('cluster', 'chunk')},
        ),
    ]
