# Generated by Django 5.1.4 on 2026-04-06 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_pr_number', models.IntegerField()),
                ('title', models.CharField(max_length=1024)),
                ('author', models.CharField(max_length=255)),
                ('base_branch', models.CharField(max_length=255)),
                ('head_branch', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged'), ('analyzing', 'Analyzing')], default='open', max_length=20)),
                ('health_score', models.FloatField(blank=True, null=True)),
                ('debt_impact_score', models.FloatField(blank=True, null=True)),
                ('opened_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='repositories.repository')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='PrFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1024)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('finding_type', models.CharField(choices=[('security', 'Security'), ('duplicate', 'Duplicate Logic'), ('rule', 'Rule Violation'), ('complexity', 'Complexity'), ('debt_impact', 'Debt Impact')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('suggestion', models.TextField(blank=True)),
                ('github_comment_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='pr_review.pullrequest')),
            ],
            options={
                'ordering': ['severity', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repo', 'status'], name='pr_review_p_repo_id_68e4e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repo', 'github_pr_number')},
        ),
        migrations.AddIndex(
            model_name='prfinding',
            index=models.Index(fields=['pr', 'severity'], name='pr_review_p_pr_id_9391c6_idx'),
        ),
        migrations.AddIndex(
            model_name='prfinding',
            index=models.Index(fields=['pr', 'finding_type'], name='pr_review_p_pr_id_bc13a2_idx'),
        ),
    ]
