# Generated by Django 5.1.4 on 2026-04-06 17:34

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        # Enable pgvector extension — must run before any vector column is created
        VectorExtension(),
        migrations.CreateModel(
            name='CodeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1024)),
                ('chunk_name', models.CharField(max_length=255)),
                ('chunk_type', models.CharField(choices=[('function', 'Function'), ('method', 'Method'), ('class', 'Class'), ('module', 'Module')], max_length=20)),
                ('language', models.CharField(max_length=50)),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('complexity_score', models.FloatField(default=0.0)),
                ('raw_code', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_chunks', to='ingestion.commit')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_chunks', to='repositories.repository')),
            ],
            options={
                'indexes': [models.Index(fields=['repo', 'file_path'], name='parsing_cod_repo_id_c29fa6_idx'), models.Index(fields=['commit', 'file_path', 'chunk_name'], name='parsing_cod_commit__44db5e_idx'), models.Index(fields=['language'], name='parsing_cod_languag_631acf_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='code_chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
