# Generated by Django 5.1.4 on 2026-04-06 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1024)),
                ('language', models.CharField(max_length=50)),
                ('complexity_component', models.FloatField(default=0.0)),
                ('duplication_component', models.FloatField(default=0.0)),
                ('violation_component', models.FloatField(default=0.0)),
                ('cluster_component', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('velocity', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_scores', to='ingestion.commit')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_scores', to='repositories.repository')),
            ],
            options={
                'indexes': [models.Index(fields=['repo', 'file_path', '-recorded_at'], name='debt_debtsc_repo_id_a346f0_idx'), models.Index(fields=['repo', '-total_score'], name='debt_debtsc_repo_id_fa24fa_idx'), models.Index(fields=['repo', '-velocity'], name='debt_debtsc_repo_id_d4496a_idx')],
                'unique_together': {('repo', 'commit', 'file_path')},
            },
        ),
    ]
