# Generated by Django 5.1.4 on 2026-04-06 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_id', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_tasks', to='repositories.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha', models.CharField(max_length=40, unique=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('committed_at', models.DateTimeField()),
                ('files_changed', models.IntegerField(default=0)),
                ('debt_score_delta', models.FloatField(default=0.0)),
                ('is_processed', models.BooleanField(default=False)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='repositories.repository')),
            ],
            options={
                'ordering': ['committed_at'],
                'indexes': [models.Index(fields=['repo', 'committed_at'], name='ingestion_c_repo_id_22cf9b_idx'), models.Index(fields=['repo', 'is_processed'], name='ingestion_c_repo_id_9e34cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PipelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('items_processed', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_events', to='repositories.repository')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repo', 'stage', '-created_at'], name='ingestion_p_repo_id_d5ab5c_idx')],
            },
        ),
    ]
