# Generated by Django 5.1.4 on 2026-04-07 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('repositories', '0002_setup_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1024)),
                ('content_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_commit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprinted_files', to='ingestion.commit')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_fingerprints', to='repositories.repository')),
            ],
            options={
                'indexes': [models.Index(fields=['repo', 'file_path'], name='ingestion_f_repo_id_0ef971_idx')],
                'unique_together': {('repo', 'file_path')},
            },
        ),
    ]
